Components/DoneListViewComponent.cs
using System.Collections.Generic;
using ToDoList.Models;
using Microsoft.AspNetCore.Mvc;
using ToDoList.ViewModels;
using ToDoList.AuxiliaryClasses;


namespace ToDoList.Components
{
    public class DoneListViewComponent : ViewComponent
    {
        //подключаем контекст данных
        private UserContext db;
        public DoneListViewComponent(UserContext context)
        {
            db = context;            
        }      

        public IViewComponentResult Invoke()
        {            
            //заводим вспомогательный класс, чтобы не писать лишний код
            CurrentUserInfo currentUser = new CurrentUserInfo();

            //получаем список сделанных дел авторизированного пользователя 
            List<DoneCase> doneList = currentUser.GetUserDoneList(db);
          
            //DCL - DeleteCasesList
            DelCasesList currentDCL = new DelCasesList { delCL = doneList };

            //и проверяем выборку на null - если новый пользователь или у него нет дел
            if (doneList == null)
                ViewBag.DoneList = "";
            else
                ViewBag.DoneList = doneList;

            return View(currentDCL);
        }
    }
}

Components/ToDoListViewComponent.cs
using System.Collections.Generic;
using ToDoList.Models;
using Microsoft.AspNetCore.Mvc;
using ToDoList.AuxiliaryClasses;


namespace ToDoList.Components
{
    public class ToDoListViewComponent : ViewComponent
    {
        //подключаем контекст данных
        private UserContext db;
        public ToDoListViewComponent(UserContext context)
        {
            db = context;
        }

        public IViewComponentResult Invoke()
        {
            //заводим вспомогательный класс, чтобы не писать лишний код
            CurrentUserInfo currentUser = new CurrentUserInfo();

            //получаем список будущих дел авторизированного пользователя 
            List<ToDoCase> toDoList = currentUser.GetUserToDoList(db);
            //и проверяем выборку на null - если новый пользователь или у него нет дел
            if (toDoList == null)
                ViewBag.ToDoList = "";
            else
                ViewBag.ToDoList = toDoList;

            return View();
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;
using ToDoList.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using ToDoList.ViewModels;
using ToDoList.AuxiliaryClasses;

namespace ToDoList.Controllers
{
    public class HomeController : Controller
    {
        //подключаем контекст данных
        private UserContext db;
        public HomeController(UserContext context)
        {
            db = context;
        }

        [Authorize]
        [HttpGet]
        public IActionResult Index()
        {   
            return View();
        }

   

        [HttpPost]
        public async Task<IActionResult> AddCase(AddCaseModel addModel)
        {
            if (ModelState.IsValid)
            {
                //заводим вспомогательный класс, чтобы не писать лишний код
                CurrentUserInfo currentUser = new CurrentUserInfo();
                //получаем id пользователя
                int userId = currentUser.GetUserId(db);
                //и добавляем дело из модели в базу
                ToDoCase caseToAdd = new ToDoCase { Case = addModel.modelCase, UserId = userId };
                db.ToDoCases.Add(caseToAdd);
                await db.SaveChangesAsync();

                return RedirectToAction("Index");
            }

            return View("Index");
        }

    

        [HttpPost]
        public async Task<IActionResult> DeleteCases(DelCasesList deleteCasesModel)
        {            
            //заводим вспомогательный класс, чтобы не писать лишний код
            CurrentUserInfo currentUser = new CurrentUserInfo();
            //получаем id пользователя
            int userId = currentUser.GetUserId(db);

            List<DoneCase> tempDoneCasesList = currentUser.GetUserDoneList(db);
            //удаляем из базы все сделанные дела, чтобы потом добавить выбранные пользователем
            db.DoneCases.RemoveRange(tempDoneCasesList);            

            //выгружаем список сделанных дел из формы
            List<DoneCase> fullDelCasesList = deleteCasesModel.delCL;            
            
            //обработка null - при пустом списке на удаление
            if (fullDelCasesList == null)
            {
                ViewBag.DoneList = "";
                return View("Index");
            }

            //заводим список для невыбранныз дел
            List<DoneCase> uncheckedCases = new List<DoneCase>();
            //добавим неывбранные дела и id пользователя в список              
            foreach (DoneCase d in fullDelCasesList)
            {
                if (d.Selected == false) 
                {
                    if(d.Case != null)
                    {
                        DoneCase tempCase = new DoneCase { Case = d.Case, UserId = userId };
                        uncheckedCases.Add(tempCase);
                    }
                }   
            }
            
            //и добавляем этот список в базу  
            db.DoneCases.AddRange(uncheckedCases);
            await db.SaveChangesAsync();

            return RedirectToAction("Index"); 
        }

        

        [HttpPost]
        public async Task<IActionResult> SaveToDbOnSort(string doneSpans, string todDoSpans)
        {
            //заводим вспомогательный класс, чтобы не писать лишний код
            CurrentUserInfo currentUser = new CurrentUserInfo();
            //получаем id пользователя
            int userId = currentUser.GetUserId(db);

            //проверям список сделанных дел из пердставления
            if (doneSpans == "")
            {
                ViewBag.DoneList = "";
            }
            //и если он не пуст, добавляем его в базу, предварительно удалив старый
            else
            {
                List<DoneCase> doneListToRemove = currentUser.GetUserDoneList(db);
                db.DoneCases.RemoveRange(doneListToRemove);
                string[] spanStings = doneSpans.Split('|');
                foreach (string s in spanStings)
                {
                    //отбрасываем возможные пустые и неправильные значения, т.к. в атрибутах верификации значение не может быть короче двух символов
                    if (s.Length > 1)
                    {
                        DoneCase tempCase = new DoneCase { Case = s, UserId = userId };
                        db.DoneCases.Add(tempCase);
                    }
                }
            }

            //то же самое делаем со списком будущих дел из представления
            if (todDoSpans == "")
            {
                ViewBag.ToDoList = "";
            }
            else
            {
                List<ToDoCase> toDoListToRemove = currentUser.GetUserToDoList(db);
                db.ToDoCases.RemoveRange(toDoListToRemove);
                string[] spanStrings = todDoSpans.Split('|');
                foreach (string s in spanStrings)
                {
                    //отбрасываем возможные пустые и неправильные значения, т.к. в атрибутах верификации значение не может быть короче двух символов
                    if (s.Length > 1)
                    {
                        ToDoCase tempCase = new ToDoCase { Case = s, UserId = userId };
                        db.ToDoCases.Add(tempCase);
                    }
                }
            }

            //и сохраняем базу
            await db.SaveChangesAsync();

            return View("Index");
        }


        public async Task<IActionResult> Logout()
        {
            //убираем аутентификацию из кук
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            //переводим на страницу логина
            return RedirectToAction("Login", "Account");
        }

    }
}

Views/Home/Index.cshtml
@using ToDoList.ViewModels;
@using ToDoList.Components; 

@model ToDoList.ViewModels.AddCaseModel

@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js" integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU=" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container-fluid">
        <form asp-action="Logout" asp-controller="Home" class="form-group">
            <div class="form-group">
                <input type="submit" value="Выйти" class="btn btn-info" />
            </div>
        </form>
    </div>

    <div class="container">
        <div class="row">
            @await Component.InvokeAsync("ToDoList")  
        </div>
    </div>

    <form asp-action="AddCase" asp-controller="Home" method="post">
        <div class="validation" asp-validation-summary="ModelOnly"></div>
        <div class="container">
            <div class="row">

                <div class="input-group">
                    <!-- в input используется name вместо asp-for, тк в index не очищается введенная стока  -->
                    <input type="text" name="modelCase" id="caseToAdd" class="form-control" placeholder="Что планируете сделать?" data-valmsg-replace="true" />
                    <div class="input-group-btn">
                        <button type="submit" id="btnCaseToAdd" class="btn btn-primary">Добавить</button>
                    </div>
                </div>
                <div class="row">                    
                    <span asp-validation-for="modelCase" class="text-danger"></span>
                </div>

            </div>
        </div>
    </form>

    <form asp-action="DeleteCases" asp-controller="Home" method="post">
        <div class="container">
            <div class="row">
                @await Component.InvokeAsync("DoneList")
            </div>
            <div class="row justify-content-left text-left">
                <div class="col-12">
                    <button type="submit" id="btnCasesToDel" class="btn btn-info">Удалить лишние</button>
                </div>
            </div>
        </div>
    </form>


    <script>

        /*функция клика по списку будущих дел */
        var moveToDoneList = function () {
            var task = $(this).text();
            var span = $('<span />').text(task);
            var cb = $('<input type="checkbox" />');
            var li = $('<li class="h4 ui-sortable-handle" />').append(cb).append(' ').append(span);
            $('#doneList').append(li);
            $(this).parent().remove();
            span.click(moveToNotDoneList);

            $(savePositionsForController);

        };

        /*функция клика по списку сделанных дел */
        var moveToNotDoneList = function () {
            var task = $(this).text();
            var span = $('<span />').text(task);
            var li = $('<li class="h4 ui-sortable-handle" />').append(span);
            $('#notDoneList').append(li);
            $(this).parent().remove();
            span.click(moveToDoneList);

            $(savePositionsForController);

        };

        /*функция для сохранения сортировки между списками и вызова контроллера(сохранение в базу) */
        var savePositionsForController = function () {
            /* присваиваем переменной не пустое значение, чтобы не было null в контроллере,
             * там это значение отсекается т.к. в атрибутах верификации значение не может быть короче двух символов */
            var doneListForController = "0";
            $('#doneList li span').each(function () {
                doneListForController = doneListForController + '|' + $(this).text();
            });

            /* присваиваем переменной не пустое значение, чтобы не было null в контроллере, 
             * там это значение отсекается т.к. в атрибутах верификации значение не может быть короче двух символов */
            var toDoListForController = "0";
            $('#notDoneList li span').each(function () {
                toDoListForController = toDoListForController + '|' + $(this).text();
            });

            $.post("@Url.Action("SaveToDbOnSort", "Home")", { doneSpans: doneListForController, todDoSpans: toDoListForController }, function () {                
                    window.location.reload();                
            });     
        };

      
        $('#notDoneList li span').click(moveToDoneList);
        $('#doneList li span').click(moveToNotDoneList);

        /* скрываем кнопку, если список сделанных дел пуст */
        $(function () {
            if ($('#doneList li span').toArray().length == 0) {
                $('#btnCasesToDel').attr('hidden', ':hidden');
            }
        });


        /* БОНУС - перетаскивание внутри списка и межнду списками */
        $(function () {
            $('.ui-sortable-handle').sortable({               
                connectWith: ".ui-sortable-handle", 
                stop: savePositionsForController
            });
        });

    </script>


</body>
</html>